### ISSUE TITLE
v1.4.1: Role "net-attach-defs-create" fails during installation

### ISSUE THREAD

**Issue by rihabbanday** [intel/container-experience-kits#66]
The task defined in net-attach-defs-create role `install pip module to manage K8s objects (satisfy requirement of the k8s_raw module` fails with the error message:

`Found existing installation: PyYAML 3.10\n\n:stderr: DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support\nERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.`

This can be fixed by adding

`extra_args: --ignore-installed PyYAML'` 
 
to the respective task in 

`roles/net-attach-defs-create/tasks/main.yml`

**Comment by przemeklal** [comment]
Hi @rihabbanday, thanks for your report and the workaround. We'll resolve it in the upcoming release. Thanks for using BMRA!
