### ISSUE TITLE
tas_install fails due to out of date helm repo location

### ISSUE THREAD

**Issue by newton-j** [intel/container-experience-kits#69]
tas install fails at task `tas_install : add Helm stable repo` as the repo location is out of date.

Can be fixed by updating the repo to: https://charts.helm.sh/stable

For more info see: https://helm.sh/blog/new-location-stable-incubator-charts/

**Comment by jagibso2** [comment]
will be addressed in point release end of Jan

**Comment by jagibso2** [comment]
Fixed with v2.1.0 release.
