### ISSUE TITLE
deployment fails while using passwordless sudo user

### ISSUE THREAD

**Issue by moss2k13** [intel/container-experience-kits#70]
Hello!
At the moment, deploying CEK (v21.08) works only when ansible connects using root's user.
When I want to deploy it using other passwordless sudo enabled user (centos/ubuntu), it fails in multiple places:
`ansible-playbook -i examples/full_nfv/inventory.ini playbooks/full_nfv.yml`
My inventory:
```
[all]
mossapio-k8s-master-1 ansible_user=ubuntu
mossapio-k8s-node-1 ansible_user=ubuntu
localhost

[kube-master]
mossapio-k8s-master-1

[etcd]
mossapio-k8s-master-1

[kube-node]
mossapio-k8s-master-1
mossapio-k8s-node-1

[k8s-cluster:children]
kube-master
kube-node

[calico-rr]

[all:vars]
ansible_python_interpreter=/usr/bin/python3
```

I'll provide full ansible log later with the 1st encountered error.

**Comment by moss2k13** [comment]
```
TASK [bootstrap/configure_proxy : set /etc/environment proxy settings] ************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 13] Permission denied: b'/tmp/tmpiztwwro3' -> b'/etc/environment'
failed: [mossapio-k8s-node-1] (item={'key': 'http_proxy', 'value': ''}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": {
        "key": "http_proxy",
        "value": ""
    }
}

MSG:

The destination directory (/etc) is not writable by the current user. Error was: [Errno 13] Permission denied: b'/etc/.ansible_tmpqv28rod8environment'
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 13] Permission denied: b'/tmp/tmpeztonoce' -> b'/etc/environment'
```

**Comment by jklare** [comment]
For me this looks like there are a couple of places where roles or tasks are called without the necessary `become: yes` (in case the user is not root). As a quick fix to get running, you can add the lines below to your ansible.cfg (or provide them via the cli):

```
[privilege_escalation]
become_ask_pass = False
```

I will try to find some time later this week to walk through the playbooks and propose a patch to add the necessary `become: yes` where needed (which will still work for root, but additionally also for non root users).

**Comment by Mionsz** [comment]
@moss2k13 Have you resolved the issue already? The workflow for non-VM installation that works for our team is adding `--become -K --become-user=root` to the command line, so in your case this would look like:

`ansible-playbook -i examples/full_nfv/inventory.ini playbooks/full_nfv.yml --become -K --become-user=root`

The `-K` parameter forces to ask you for password on start and if you use password-less `sudo` just confirm with empty password.

**Comment by moss2k13** [comment]
thanks for info, I'll give it a try after new years eve once I'll be back at the office. I'll update you here

**Comment by Mionsz** [comment]
@moss2k13 any updates? Can we close the issue?

**Comment by moss2k13** [comment]
thanks for reminder, I forgot to update you here, we can close it

**Comment by Mionsz** [comment]
@moss2k13 Thanks for the quick update :-)!
@michaelspedersen Can you close it?

**Comment by michaelspedersen** [comment]
> @moss2k13 Thanks for the quick update :-)! @michaelspedersen Can you close it?

I can't, but @calinghe should be able to :)

**Comment by calinghe** [comment]
Closing based on the above comments.  Thank you, all!
