### ISSUE TITLE
missing Makefile

### ISSUE THREAD

**Issue by jklare** [intel/container-experience-kits#72]
Walking through the latest README of the release 21.09 i found that it now mentions to use `make` to generate the example host_vars, group_vars and the inventory. Currently this is not possible since this there is no Makefile in this repository. This commit 9b9a465f0a7c188b043cbe77917f3f99e1524f87 changes the README, but does not add the needed Makefile (maybe it was forgotten to add it?).

**Comment by calinghe** [comment]
Thanks much for your input, @jklare.  We'll generate a hotfix to address this issue.

**Comment by jagibso2** [comment]
pushed missing Makefile.  Please verify and close.
https://github.com/intel/container-experience-kits/commit/3a27e8ad7c9ca0424192460e427cefb235d767a2

**Comment by calinghe** [comment]
Hi @jklare.  We think this issue was addressed and we're closing it.  If still persists, please reopen.  Thanks again for your submission.
