### ISSUE TITLE
install dependencies on localhost

### ISSUE THREAD

**Issue by jklare** [intel/container-experience-kits#73]
Currently the playbooks (e.g. remote_fp) assume that they can and should install certain dependencies on localhost. Since most people run ansible from their local machine (e.g. their desktop, laptop or macbook), this means that the current playbooks try to modify the machines that they run on and not only the remote machines they should deploy.

https://github.com/intel/container-experience-kits/blob/master/playbooks/infra/remote_fp.yml#L17-L23
https://github.com/intel/container-experience-kits/blob/master/roles/bootstrap/ansible_host/tasks/main.yml

In my opinion this leads to a couple of issues:
1) privilege escalation on localhost (so on my local machine) is something that i never want to grant to an ansible playbook downloaded from the internet (due to very basic security considerations) and imho it should never be needed
2) my local environment might look very different from what the playbook expects (e.g. using venv or having my python dependencies in a different path)
3) modifications on my local system should be left to me, or to be a bit more generic here: any modifications needed to run ansible playbooks should be mentioned in the docs, there might be a script or even an playbook to help, but this should not be forced by default

In conclusion i think the whole part of installing dependencies should be moved to documentation or at least made optional and be disabled by default.

**Comment by jagibso2** [comment]
agree...will review and update accordingly

**Comment by calinghe** [comment]
Thanks again @jklare for your submission.  Our next release BMRA 22.01 will address this and contributor license will also be added to encourage further contributions.  However, we're not planning to patch the current 21.09 for this purpose.

**Comment by jagibso2** [comment]
see https://github.com/intel/container-experience-kits/releases/tag/v22.01
