### ISSUE TITLE
configure_intel_pstate does not reboot after changing grub config

### ISSUE THREAD

**Issue by jklare** [intel/container-experience-kits#74]
Currently the tasks in the role boostrap/configure_intel_pstate change the grub config (https://github.com/intel/container-experience-kits/blob/master/roles/bootstrap/configure_intel_pstate/tasks/setup_intel_pstate.yml#L29-L38) and notify the reboot handler. By default all notifications will only be executed at the end of the playbook run (or at the end of the role in this case. This means, that by default the task that checks for certain states depending on those grub changes (https://github.com/intel/container-experience-kits/blob/master/roles/bootstrap/configure_intel_pstate/tasks/setup_turbo.yml#L37-L52) will fail, because the reboot handler has not been executed yet. I think this can be solved by flushing the handlers like described here (https://docs.ansible.com/ansible/latest/user_guide/playbooks_handlers.html#controlling-when-handlers-run) after the configuration is done and before the checks are run (e.g. here https://github.com/intel/container-experience-kits/blob/master/roles/bootstrap/configure_intel_pstate/tasks/main.yml#L31)

**Comment by calinghe** [comment]
Thank you @jklare for this report and suggested solution.  We're looking into it.

**Comment by calinghe** [comment]
Fixed since RA 22.05
