### ISSUE TITLE
deduplicate the code within the PROFILE specific playbooks

### ISSUE THREAD

**Issue by jklare** [intel/container-experience-kits#78]
Currently there are 6 different flavours of deployment available (basic, access, full_nfv, on_prem, regional_dc and remote_fp). To use those flavours, there are currently 6 almost identical playbooks in the playbooks/ folder. The only difference between those playbooks is the name of the `infra/` and `intel/` playbook they import. Looking further down into those playbooks, there is also a large amount of similarities between those `infra` and `intel` playbooks that are meant to be specific for the chosen profile.
This amount of code duplication makes it unnecessarily complicated to add, update or refactor common parts, since those need to always be updated 6 times, to be reflected in all playbooks. In addition to that, the chance of a fix or refactoring step to only make it into one of those playbooks is pretty high.
To fix this issue, my current suggestion would be to introduce a variable in the inventory like `profile=` and ask the user (or the render.py) to set this variable to the chosen `$PROFILE`.
After that, it should be possible to merge all the profile specific playbooks into one common one for the main playbook, which would call the common ones for `intel/` and `infra/`. Within those `intel/` and `infra/` playbooks, it should be possible to evaluate the value of the new `profile=` variable in conditionals (e.g. `when:`) to only run specific tasks for specific profiles.
Please let me know if you like the general idea and if so, how we can coordinate the needed work to walk into this direction.

**Comment by jagibso2** [comment]
Thanks for suggestion.  will look into it

**Comment by calinghe** [comment]
Thanks again @jklare for your submissions.  The fix is WIP and expected to be included into the next release (22.01).

**Comment by jagibso2** [comment]
see https://github.com/intel/container-experience-kits/releases/tag/v22.01
