### ISSUE TITLE
using role/vars/main.yml to set defaults makes changing almost impossible

### ISSUE THREAD

**Issue by jklare** [intel/container-experience-kits#79]
Currently a lot of the included roles (like bootstrap/configure_security/ or bootstrap/update_nic_firmware) use `vars/main.yml` to define the default variable values, instead of using `defaults/main.yml`. Following the precedence order defined here https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#understanding-variable-precedence, this makes it very hard to override those variable values (in case you need to open an additional port in your firewall or use a different firmware). IHMO most of those variables should be considered defaults, and should be moved to `defaults/main.yml` to allow the user to set them directly from `group_vars/all.yml` or `host_vars/node1.yml`, instead of requiring them to be passed on a even higher precedence (>15).

**Comment by calinghe** [comment]
Thanks much for bringing up this issue and your recommendation, @jklare.  We'll get this addressed into the next release (22.01)

**Comment by jagibso2** [comment]
see https://github.com/intel/container-experience-kits/releases/tag/v22.01.  Please file issue against individual role, if any still exist
