### ISSUE TITLE
About removed support for CMK

### ISSUE THREAD

**Issue by f18m** [intel/container-experience-kits#83]
Hi,
I noticed that in release 22.01 the support for Intel CPU Manager for Kubernetes (CMK) has been removed.
I have a DPDK application in kubernetes that is using it so I wondered why Intel has decided to remove the support for it... should I use instead the --cpu-manager=static option builtin in Kubelet? 
Or there's some other replacement that is more appropriate for CPU pinning in Kubernetes?

Thanks!

**Comment by jagibso2** [comment]
@f18m  Latest K8S releases support native CPU manager as replacement for CMK.  Please ensure your host_vars enables it.  As commented in host_vars file, 'static' policy will be enabled by default.

native_cpu_manager_enabled: true
